name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    env:
      TARGET: x86_64-unknown-linux-musl

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        echo 123 > kak-lsp-$(git describe --tags)-$TARGET.tar.gz
        # ci/all.sh

    - uses: actions/upload-artifact@v2
      with:
        name: kak-lsp-$(git describe --tags)-$TARGET.tar.gz
        path: kak-lsp-$(git describe --tags)-$TARGET.tar.gz


  # macos:

  #   runs-on: macos-latest

  #   env:
  #     TARGET: x86_64-apple-darwin
    
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Build
  #     run: ci/all.sh
